.TH SENSOR-DS18B20 1
.SH NAME
sensor-ds1b20 \- read DS18B20 sensors attached to the 1-Wire bus
.SH SYNOPSIS
.B sensor-ds18b20
.SH DESCRIPTION
.B sensor-ds18b20
Reads temperature data from DS18B20 sensors attached to the 1-Wire bus (default GPIO pin is 17).
.SH OPTIONS
.TP
None
.SH NOTES
This program is designed to be used with the \fBsr\fR program (sensor-read) from WildlifeSystems.
