#!/bin/bash

wget https://raw.githubusercontent.com/Wildlife-Systems/sensor-ds18b20/refs/heads/main/sensor-ds18b20
chown root:root sensor-ds18b20
chmod +x sensor-ds18b20
mv sensor-ds18b20 /usr/bin

# Function to get location of config.txt
function get_config_txt {
        if [ -f /boot/firmware/config.txt ]; then
                echo "/boot/firmware/config.txt"
        else
                echo "/boot/config.txt"
        fi
}

config_txt=$(get_config_txt)
cnt=$(grep -c "dtoverlay=w1-gpio,gpiopin=17,pullup=1" "$config_txt")
if [[ "$cnt" -eq 0 ]]; then
  sudo sh -c "echo '# Enable 1-Wire interface on pin 17
dtoverlay=w1-gpio,gpiopin=17,pullup=1' >> $config_txt"
fi

# Suggest reboot
echo "Please reboot the system to apply changes."
